language: python
python:
- '3.7'
jobs:
  include:
  - stage: test and lint
    name: python lint
    python: '3.7'
    install:
    - pip install pipenv
    - pipenv install -d
    script:
    - pipenv run flake8 .
  - name: python test
    if: type != pull_request
    python: '3.7'
    before_install:
    - openssl aes-256-cbc -K $key -iv $iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    install:
    - pip install pipenv
    - pipenv install -d
    script:
    - pytest
  - name: js test
    language: node_js
    node_js: lts/*
    script:
    - npm run test
  - stage: release
    name: deploy to gae
    if: branch = master AND repo = creek0810/loveat2 AND fork = false
    python: 3.7
    script: echo "Deploying to gae ..."
    install:
    - pip install pipenv
    before_deploy:
    - pipenv lock -r > requirements.txt
    before_install:
    - openssl aes-256-cbc -K $key -iv $iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    deploy:
      provider: gae
      skip_cleanup: true
      keyfile: client-secret.json
      project: loveat2
      on:
        branch: master
  - name: release to github
    language: node_js
    node_js: lts/*
    script:
    - npm run semantic-release